import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth/next";
import { authOptions, options } from "./api/auth/[...nextauth]/authOptions";

import { SidebarProvider } from "../context/SidebarContext";
import AuthProvider from "../context/AuthProvider";
import NavBar from "../components/NavBar";
import SignInButton from "../components/SignInButton";
import SideNavbar from "../components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-CommerceAdmin",
  description: "Generated by PKG",
};
const Logo ='/Logo-Camel.jpg'

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
          <AuthProvider>
            {session ? (
              <SidebarProvider>
                <div className="layout">
                  <SideNavbar logo={ Logo } title={ metadata.title } />

                  <main className="layout__main-content">{children}</main>
                </div>
              </SidebarProvider>
            ) : (
              // <>
              //   <NavBar />

              //   <main className="bg-white flex-grow mt-2 mr-2 mb-2 p-4 rounded-lg">
              //     {children}
              //   </main>
              // </>
              <SignInButton />
            )}
          </AuthProvider>
      </body>
    </html>
  );
}
