import { Inter } from "next/font/google";
import "./globals.css";

import { getServerSession } from "next-auth/next";
import { options } from "./api/auth/[...nextauth]/options";

import AuthProvider from "../components/context/AuthProvider";
import NavBar from '../components/NavBar'
import SignInButton from "../components/SignInButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Commerce",
  description: "Generated by PKG",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(options)  

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          { session ? 
          (<>
          <NavBar />

          <main className="bg-white flex-grow mt-2 mr-2 mb-2 p-4 rounded-lg">
            {children}
          </main>

          </>)
          : (
            <SignInButton />
          )
          }
        </AuthProvider>
      </body>
    </html>
  );
}
